  # collections:
  #  - ansible.tower

  # tasks:
  # - name: Create a new organization
  #   tower_organization:
  #     name: "TestORG"
  #     description: "test org"
  #     state: present

  - name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
