---
- name: Convert
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  vars:
    rhsm_username: "{{ RHSM_USERNAME }}"
    rhsm_password: "{{ RHSM_PASSWORD }}"
    rhsm_org: "{{ RHSM_ORG }}"
    rhsm_activation_key: "{{ RHSM_ACTIVATION_KEY }}"

  tasks:
    - name: Perform OS conversion
      ansible.builtin.import_role:
        name: infra.convert2rhel.convert
