---
- name: Upgrade
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  vars:
    satellite_organization: UBA Group
    satellite_activation_key_leapp: Satellite Activation Key
    satellite_activation_key_post_leapp: Satellite Activation Key
    leapp_upgrade_opts: --target 8.10
    update_grub_to_grub_2: true
    selinux_mode: permissive
  tasks:
    - name: Perform OS upgrade
      ansible.builtin.import_role:
        name: infra.leapp.upgrade
