---
- name: Upgrade
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  vars:
    satellite_organization: UBA Group
    satellite_activation_key_leapp: Satellite Activation Key
    satellite_activation_key_post_leapp: Satellite Activation Key
    leapp_upgrade_opts: --target 8.10
    update_grub_to_grub_2: true
    selinux_mode: permissive
  tasks:
    - name: Install Leapp package
      ansible.builtin.shell: subscription-manager repos --enable rhel-7-server-extras-rpms
      
    - name: Install leapp and leap Upgrade
      yum:
        state: present
        name:
          - leapp
          - leapp-upgrade

    - name: Create the answer file
      ansible.builtin.shell: echo '[remove_pam_pkcs11_module_check] \n confirm = True ' >> /var/log/leapp/answerfile

    - name: Run the leapp preupgrade report
      ansible.builtin.shell: leapp preupgrade
        
    - name: Perform OS upgrade
      ansible.builtin.import_role:
        name: infra.leapp.upgrade
