---
- name: Upgrade
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  vars:
    satellite_organization: {{ SATELLITE_ORGANIZATION }}
    satellite_activation_key_leapp: {{ SATELLITE_ACTIVATION_KEY }}
    satellite_activation_key_post_leapp: {{ SATELLITE_ACTIVATION_KEY_POST }}
    leapp_upgrade_opts: --target 8.8
    update_grub_to_grub_2: true
    selinux_mode: permissive
  tasks:
    - name: Perform OS upgrade
      ansible.builtin.import_role:
        name: infra.leapp.upgrade